---
title: "Talks"
output: html_document
---

## Conferences---Invited talks


1. **Aleksić, D.** (2025). Testing goodness-of-fit, independence and MCAR on incomplete dataset utilising the properties of non-degenerate and weakly-degenerate U- and V-statistics. *24th European Young Statisticians Meeting, Torino, 21-25 July 2025.* \
   <https://sites.google.com/view/eysmtorino2025/book-of-abstracts>, page 15.

2. **Aleksić, D.** (2023). A new approach to Little's MCAR test. *CMStatistics, Berlin, 13-15 December 2023.* \
   <https://www.cmstatistics.org/CMStatistics2023/docs/BoA.pdf?20231128014621>, page 43.


## Conferences---Other talks

1. **Aleksić, D.G.** (2025). Flexible MCAR testing for missing data with correlated response indicators. *XV Symposium "Mathematics and Applications", Faculty of Mathematics, University of Belgrade, 12-13 December 2025.*\
   <https://simpozijum.matf.bg.ac.rs/s2025/AleksicDanijel.pdf>

2. **Aleksić, D.**, Cuparić, M., Milošević, B. (2025). Asymptotic results for some U- and V-statistics for model specification testing under missing data. *3rd Joint Mathematical Meeting of Serbia and Montenegro, Petrovac, 02-05 October 2025* (presenting author: Aleksić, D.)

3. **Aleksić, D.**, Milošević, B. (2025). Homogeneity testing in the presence of missing data. *Workshop on Goodness-of-fit, Change-point and Related Problems, Prague, 28-31 August 2025* (presenting author: Milošević, B.)\
   <https://gofcp.karlin.mff.cuni.cz/GOFCP_book_of_abstracts.pdf>, page 21.

4. Milošević, B., **Aleksić, D.** (2025). Energy-distance-based two-sample testing in the presence of incomplete data. *HiTEc & Codes, Limassol, 8-9 July 2025* (presenting author: Milošević, B.) \
   <https://www.cmstatistics.org/hiteccodes2025/fullprogramme.php>

5. **Aleksić, D.**, Milošević, B. (2024). Addressing missing data challenges: A multivariate goodness-of-fit testing perspective. *6th International Symposium on Nonparametric Statistics, Braga, 25-29 June 2024* (presenting author: Milošević, B.) \
   <https://w3.math.uminho.pt/ISNPS2024/img/ISNPS%202024_PROGRAMME.pdf>, page 88.

6. **Aleksić, D.**, Milošević, B. (2024). To impute or not to? A multivariate goodness-of-fit testing perspective. *15th Serbian Mathematical Congress, Belgrade, 19-22 June 2024 (presenting author: Aleksić, D.).* \
   <https://smak15.matf.bg.ac.rs/smak15/AleksicMilosevic15Smak.pdf>

7. Cuparić, M., **Aleksić, D.**, Milošević, B. (2024). Testing independence in the presence of data missing completely at random. *The Spring HiTEc meeting and the Complex Data in Econometrics and Statistics Workshop, Limassol, Cyprus, 23-24 March 2024* (presenting author: Cuparić, M.) \
   <https://www.cmstatistics.org/hiteccodes2024/fullprogramme.php>

8. **Aleksić, D.** (2023). U-statistics-based approach for testing the MCAR assumption. *XIII Symposium "Mathematics and Applications", Faculty of Mathematics, University of Belgrade, 1-2 December, 2023.* \
    <http://simpozijum.math.rs/s2023/DanijelAleksicApstrakt.pdf>

9. **Aleksić, D.**, Cuparić, M., Milošević, B. (2023). On the asymptotic properties of non-degenerate U-statistics in the presence of MCAR data. *Statistical Modeling with Applications, Bucharest, 29-30 September 2023* (presenting author: Aleksić, D.) \
    <https://statmod2023.sciencesconf.org/data/pages/BoA_StatMod2023_WithPoster_2.pdf>, page 3.

10. **Aleksić, D.**, Milošević, B. (2023). Missing data: the impact on multivariate goodness-of-fit tests. *II Susret matematičara Srbije i Crne Gore, 26-28 january 2023* (presenting author: Aleksić, D.) \
    <https://konferencije.matf.bg.ac.rs/smscg2023/wp-content/uploads/2023/01/smscg2023-knjiga-apstrakta-1-1.pdf>, page 1.

11. Milošević, B., **Aleksić, D.** (2022). Testing multivariate normality in the presence of missing data. *CMStatistics, London, 17-19 December 2022* (presenting author: Milošević, B.) \
    <http://www.cmstatistics.org/CMStatistics2022/docs/BoACFECMStatistics2022.pdf>, page 117.

12. **Алексић, Д.**, Милошевић, Б. (2021). Утицај импутационих метода на тестове вишедимензионе нормалности. *XI Симпозијум ,,Математика и примене'', Београд, 2-3. децембар 2021* (презентујући аутор: Алексић, Д.).  ***(in Serbian)*** \
    <https://alas.matf.bg.ac.rs/~konferencija/KNJIGA_APSTRAKATA_2021.pdf>, page 1.

13. **Алексић, Д.** (2019). Однос дебљине новчића и вероватноће пада на ивицу. *X Симпозијум ,,Математика и примене'', Београд, 6-7. децембар 2019.*  ***(in Serbian)*** \
    <https://alas.matf.bg.ac.rs/~konferencija/KNJIGA_APSTRAKATA_2019.pdf>, page 37.
