---
title: "Настава"
output: html_document
---
***
У својој досадашњој наставној каријери имао сам прилику да држим наставу на следећим институцијама:

- **Факултет организационих наука у Београду:** Математика 1 *(вежбе)*, Математика 2 *(вежбе)*;
- **Математички факултет у Београду:** Статистички софтвер 3 *(вежбе)*, Теорија информације *(вежбе)*, Увод у теорију узорака *(вежбе)*, Вероватноћа и статистика Б *(вежбе)*, Увод у финансијску математику *(вежбе)*;
- **Математичка гимназија у Београду:** Анализа са алгебром *(4. разред)*.

На већини предмета служио сам се туђим уџбеницима, збиркама, скриптима итд, јер су већ постојали у тренутку када сам почео да држим предмет, били су адекватни и није било потребе да пишем своје. Ипак, неки предмети су ме дочекали потпуно ,,празни'', а неки делимично, па сам имао потребу да понешто и створим.

Испод посебно издвајам материјале чији сам ја аутор, било делимично или у целости.

***

## Математика 1 -- ФОН

### Вежбе

У наставку се могу наћи материјали за вежбе из Математике 1 који су настали у току школске 2025/26. године у сарадњи са колегиницом Дуњом Прокић са Катедре за математику ФОН-а. Кликом на наслов активира се веза која води ка одговарајућем PDF документу. 

На основу материјала ће настати збирка задатака, која ће се по садржају минимално разликовати од њих, али ће се по форми и стилу разликовати значајно. При изради збирке у обзир су узети сви студентски коментари. 

Слично градиво обрађује се на уводним курсевима математике на скоро свим техничким факултетима, па верујем да многима може бити на корист.


[Вежбе 1: Алгебарске структуре](m1Vezbe/m1Vezbe01sr.pdf)

[Вежбе 2: Матрице и детерминанте](m1Vezbe/m1Vezbe02sr.pdf)

[Вежбе 3: Матричне једначине, ранг матрице](m1Vezbe/m1Vezbe03sr.pdf)

[Вежбе 4: Системи линеарних једначина](m1Vezbe/m1Vezbe04sr.pdf)

[Вежбе 5: Векторски простори](m1Vezbe/m1Vezbe05sr.pdf)

[Вежбе 6: Раван](m1Vezbe/m1Vezbe06sr.pdf)

[Вежбе 7: Права](m1Vezbe/m1Vezbe07sr.pdf)

[Вежбе 8: Гранична вредност низа](m1Vezbe/m1Vezbe08sr.pdf)

[Вежбе 9: Тачке нагомилавања низова](m1Vezbe/m1Vezbe09sr.pdf)

[Вежбе 10: Гранична вредност и непрекидност функције](m1Vezbe/m1Vezbe10sr.pdf)

[Вежбе 11: Извод функције](m1Vezbe/m1Vezbe11sr.pdf)

[Вежбе 12: Тејлоров и Маклоренов полином](m1Vezbe/m1Vezbe12sr.pdf)

[Вежбе 13: Испитивање тока и скицирање графика функције](m1Vezbe/m1Vezbe13sr.pdf)

***

## Статистички софтвер 3 -- МАТФ

Курс је практичног карактера и има само вежбе. Тиче се увода у статистичко и машинско учење. 

На следећем [линку](ss3.pdf) могу се пронаћи скрипта која сам писао за потребе практичне наставе. Материјал за прве три наставне недеље недостаје, јер се тренутак истека уговора мог претходника на курсу, др Жикице Лукића, погодио тако несрећно да сам га преузео тек од четврте недеље. 

Сходно томе да је због пандемије Covid--19 настава одржавана на даљину, материјали су писани хитно и брзо: већина слика је преузета са интернета, кодови су форматирани минимално. Постоји доста терминолошких и других грешака. Ипак, тада су послужили сврси, па их нека и овде, можда некоме могу бити на корист.

***

## Теорија информације -- МАТФ

Следећи [линк](http://old.matf.bg.ac.rs/p/danijel-aleksic/kurs/941/%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD-%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD/) води ка мојој некадашњој МАТФ страни на којој се, поред видео материјала који су линковани у наставку, могу пронаћи и неки писани материјали који могу бити од користи.

### Вежбе

У наставку су линкови ка видео материјалима које сам приредио за потребе наставе на даљину у условима у току и непосредно након пандемије Covid--19. Покривене су комплетне вежбе; због комплетности, пре сваке практичне лекције дат је кратак теоријски увод који служи брзом упознавању са појмовима везаним за дату лекцију.

1. [Информација -- теоријски увод](https://www.youtube.com/watch?v=v6ysLYHVT1w&t=742s)
2. [Неодређеност (ентропија) -- теоријски увод](https://www.youtube.com/watch?v=yey3TmtszkA)
3. [Неодређеност и информација -- Задаци 1](https://www.youtube.com/watch?v=2u_7_6y_XDc)
4. [Неодређеност и информација -- Задаци 2](https://www.youtube.com/watch?v=J636b6Hupjs)
5. [Неодређеност и информација -- Задаци 3](https://www.youtube.com/watch?v=k7RIkHVNcA0)
6. [Неодређеност и информација -- Задаци 4](https://www.youtube.com/watch?v=ZxoMyGFb2qU)
7. [Извори информације -- Теоријски увод](https://www.youtube.com/watch?v=Kj29-LfxPkM)
8. [Кодови без шума -- Теоријски увод](https://www.youtube.com/watch?v=_IRC2G-AuVA&t=730s)
9. [Кодови без шума -- Задаци](https://www.youtube.com/watch?v=OLF4VxU-7I8&t=474s)
10. [Канали везе -- Теоријски увод 1: уопштено о каналима везе](https://www.youtube.com/watch?v=FKVHDWDnkVg&t=1090s)
11. [Канали везе -- Теоријски* увод 2: Одређивање капацитета, основни задаци](https://www.youtube.com/watch?v=WqcEC7ksrzI)
12. [Канали везе -- Теоријски* увод 3: Пренос података каналом, пар основних задачића](https://www.youtube.com/watch?v=9Y3wFejZSYU&t=88s)
13. [Канали везе -- Теоријски увод 4: Фундаметална теорема теорије информације](https://www.youtube.com/watch?v=2y1iTRjMAZg&t=684s)
14. [Канали везе -- Задаци 1: Одређивање капацитета канала](https://www.youtube.com/watch?v=UrPxHPfgMIM&t=1395s)
15. [Канали везе -- Задаци 2: Правила одлучивања](https://www.youtube.com/watch?v=EbPRuSbgrRs&t=659s)
16. [Кодови који откривају грешке -- Теоријски увод и основни примери](https://www.youtube.com/watch?v=qg-7Mkkda2E&t=3359s)
17. [Кодови који исправљају грешке -- Теоријски увод 1: Хамингов код, граница Гиљберт-Варшамова](https://www.youtube.com/watch?v=BnhmUuHsEWk&t=2041s)
18. [Кодови који исправљају грешке -- Теоријски увод 2: Линеарни кодови 1](https://www.youtube.com/watch?v=ScvR0wN2D0w&t=1857s)
19. [Кодови који исправљају грешке -- Теоријски увод 3: Линеарни кодови 2, Хамингови и Голеови кодови](https://www.youtube.com/watch?v=VHR1FN2BH6s&t=1448s)
20. [Кодови који исправљају грешке -- Задаци 1: Линеарни кодови](https://www.youtube.com/watch?v=K-l7rhFiTRk&t=225s)
21. [Кодови који исправљају грешке -- Задаци 2: Хамингова и Гиљберт-Варшамовљева граница](https://www.youtube.com/watch?v=vrcJFFOvybw&t=720s)

***

## Увод у теорију узорака -- МАТФ

### Вежбе

На следећем [линку](UUTU.pdf) могу се преузети скрипта која сам сачинио у току школске 2021/22. године. за потребе практичне наставе на курсу. Скрипта покривају основне начине узорковања, њихове особине и имплементацију у програмском језику `R`. Како сам математичар, а не програмер, кодови су писани на релативно примитивном нивоу и њихова сврха је проста илустрација метода, не и препорука како методе имплементирати у пракси. 

***

